### ISSUE TITLE
Upload source code to PyPI

### ISSUE THREAD

**Issue by apcamargo** [patrickwest/EukRep#10]
Hi @patrickwest!

I'm working on uploading EukRep to conda. However, I've noticed that the the source code was not uploaded to PyPI, only the wheel.

Would it be possible to upload BinSanity's source to PyPI?

Thank you!

**Comment by apcamargo** [comment]
It can be a GitHub release too!

**Comment by tseemann** [comment]
+1 to both

**Comment by patrickwest** [comment]
Thanks for your interest! The newest version on PyPi should now have the source code. I made a github release as well.

**Comment by apcamargo** [comment]
Thanks @patrickwest!
