### ISSUE TITLE
Can eukaryotes,  prokaryotic and virus be differentiated by this software?

### ISSUE THREAD

**Issue by li0604** [patrickwest/EukRep#15]
Dear professor,

Because of the effects of eukaryotes and virus of my analysis, I want to know that can eukaryotes,  prokaryotic and virus be differentiated by this software?

Thanks a lot.

**Comment by patrickwest** [comment]
Hi li0604,

EukRep can differentiate eukaryotic and prokaryotic sequences. I have not tested where it places viruses, it may classify them as either eukaryotic or prokaryotic. I have heard anecdotally that EukRep will classify virus sequences as eukaryotic.
