### ISSUE TITLE
sklearn 0.19 compatible?

### ISSUE THREAD

**Issue by wwood** [patrickwest/EukRep#2]
Hi,

I ran EukRep on some dummy data, and got the following warning. Is this dangerous?
```
$ EukRep -i Methanoflorens_stordalmirensis_v4.3.2.genome.fna -o /dev/stdout
/gnu/store/r1sgvgidshhy8wxdfw40ayhlyvbf03bg-python-scikit-learn-0.19.0/lib/python3.5/site-packages/sklearn/base.py:312: UserWarning: Trying to unpickle estimator LinearSVC from version 0.18 when using version 0.19.0. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
```
Is there some way to test that installation has worked?
ta

**Comment by patrickwest** [comment]
Hello,

Thanks for pointing out this issue. That warning is generated when a different scikit-learn version than the one a model was trained with is being used. I don't believe it is dangerous. Prediction appears to be working as expected with scikit-learn version 0.19.0 on my system despite the warning however I'll add a test to the package and retrain the models with the next version.

Patrick
